### ISSUE TITLE
Enumerate WASAPI Audio Devices

### ISSUE THREAD

**Issue by ryan-weil** [roman380/alax.info-toolbox#1]
https://alax.info/blog/1279

Hey, didn't want to bother you on your email - was curious if you still have this program here as it doesn't appear to be present in the repository.

**Comment by roman380** [comment]
Yes, I do. Binaries and some source code (you can't build it but you would be able to copy/paste if needed).

[EnumerateAudioDevices.zip](https://github.com/roman380/alax.info-toolbox/files/9477266/EnumerateAudioDevices.zip)
